version: "3"
networks:
  lapd-net:

services:
  server:
    build: ./app
    ports:
      - "8000:8080"
    networks:
      - lapd-net
    volumes:
      - /home/sofia/feup-lapd/app:/app
      - /home/sofia/feup-lapd/app/node_modules
    depends_on:
      - postgres

  postgres:
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - lapd-net

  pgadmin:
    image: thajeztah/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_ENABLE_TLS: "False"
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    networks:
      - lapd-net
